# Generated by Django 4.1.7 on 2023-03-22 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pergunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('perguntaNivel', models.IntegerField()),
                ('pergunta', models.CharField(max_length=250)),
                ('alternativa_a', models.CharField(max_length=250)),
                ('alternativa_b', models.CharField(max_length=250)),
                ('alternativa_c', models.CharField(max_length=250)),
                ('alternativa_d', models.CharField(max_length=250)),
                ('resposta', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Puzzle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puzzleNivel', models.IntegerField()),
                ('puzzleEnunciado', models.CharField(max_length=250)),
                ('puzzleComand', models.CharField(max_length=250)),
                ('puzzleResposta', models.CharField(max_length=250)),
            ],
        ),
    ]
